AYS-333 | Solving test errors
afet-yonetim-sistemi/ays-fe-landing pull request #67
Opened 2024-08-14 19:58 UTC by NNakreSS

### Checklist

Before submitting your pull request, ensure the following:

- [ ] **Change Type:**
- [x] Bug fix
- [ ] Feature addition
- [ ] Documentation update
- [ ] Performance improvement
- [ ] Other (please specify)

- [x] **Summary:**
    - Similar phone number error has been shown to the user in a more meaningful way, the problem of deleting the number of seats 0 has been fixed, the first error messages that appear in 2 steps for the application made on behalf of someone else have been fixed.

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on my browser, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by ESLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Related Issue:**
    - #62 

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-08-15 16:41 UTC, sanshigo345 commented
branch ve pr isimleri hiç açıklayıcı değil neyi review etmeliyim anlamadım, AYS-333 ticket'ı form hazırlanması ile alakalı olarak gözüküyor.

2024-08-15 18:10 UTC, NNakreSS commented
> branch ve pr isimleri hiç açıklayıcı değil neyi review etmeliyim anlamadım, AYS-333 ticket'ı form hazırlanması ile alakalı olarak gözüküyor.

Testteki hatalarını giderilmesi olarak yazdım, detaylar summary kısmında , header değil 😄

2024-08-15 18:46 UTC, NNakreSS commented
> > > branch ve pr isimleri hiç açıklayıcı değil neyi review etmeliyim anlamadım, AYS-333 ticket'ı form hazırlanması ile alakalı olarak gözüküyor.
> > 
> > Testteki hatalarını giderilmesi olarak yazdım, detaylar summary kısmında , header değil 😄
> 
> anladım, ama AYS-333 bir feature ticket'ı iken bugfix olarak branch açılması, AYS-333 kodu kullanılarak bütün ticketı değil küçük bir kısmını kapsayan branch/pr açmak bence yanlış. @agitrubard böyle durumlarda napılabileceğine dair bi açıklama yapsın

Testten dönen task , aynı kodu kullanmak zorundayız, aksi durum olmaz zaten , farklı bir issue değil.merge sonrası branch sildiğimiz için geriye dönük update de atamayız.

2024-08-15 22:19 UTC, sanshigo345 requested changes
neden localization yok?

2024-08-15 22:19 UTC, sanshigo345 commented on src/components/EmergencyForm/OtherEvacuationForm.tsx
>  import onSubmitForm from '@/services/formService'
institution da tek icon paketi kullanmayı düşünüyoruz burda da lucide üzerinden icon bulunabilir

2024-08-15 22:21 UTC, sanshigo345 commented
<img width="635" alt="Screenshot 2024-08-16 at 01 14 59" src="https://github.com/user-attachments/assets/37a4faed-2b20-4053-b543-cc87f1f2e4bf">

jfyi: nerden geldiğini tam çözemedim bi süre sonra bu hata geliyor

2024-08-15 23:01 UTC, NNakreSS commented
> neden localization yok?

Farklı issue açık zaten , institution daki gibi yapılamaz , burada olabildiğince sayfalar serverda tutulmalı , haliyle i18 işleyişi de farklı.

2024-08-15 23:03 UTC, NNakreSS commented on src/components/EmergencyForm/OtherEvacuationForm.tsx
>  import onSubmitForm from '@/services/formService'
evet fikri sunan benim zaten 😅 , burayı yaparken diğer projedeki paketleri farklılık olmaması açısından kullanmıştım başta.

2024-08-15 23:04 UTC, NNakreSS commented on src/components/EmergencyForm/OtherEvacuationForm.tsx
Mesela , önerilere açığız , tasarım zamanında belirlendi hepsi ama ortak bir fikir ile değiştirlebilir , -> stepper mantığı o zaten , yoksa tek form yapabiliriz çok uzun oluyor , tasarıma göre gidiyoruz.

2024-08-15 23:27 UTC, NNakreSS commented
> <img alt="Screenshot 2024-08-16 at 01 14 59" width="635" src="https://private-user-images.githubusercontent.com/38170967/358415580-37a4faed-2b20-4053-b543-cc87f1f2e4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjI3NTUsIm5iZiI6MTcyMzc2MjQ1NSwicGF0aCI6Ii8zODE3MDk2Ny8zNTg0MTU1ODAtMzdhNGZhZWQtMmIyMC00MDUzLWI1NDMtY2M4N2YxZjJlNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDIyNTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0M2U4MmRiMDczNzRkNGRiZjVhNDFjNzhmMjRiMzMwYzAzZmEzYzdlMDJjYzRiNTNmYjgxZGRhNzE5MDIyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2MGqh8FMcXXOzhDS0Le90ysFByTZ0GC78XJsEjTDLk">
> jfyi: nerden geldiğini tam çözemedim bi süre sonra bu hata geliyor

deepl veya benzeri bir extension kullanıyor musun ?

2024-08-16 07:04 UTC, kevseroz submitted a review, later dismissed

2024-08-16 16:21 UTC, sanshigo345 commented on src/components/EmergencyForm/OtherEvacuationForm.tsx
AssistedEvacuationForm
ProxyEvacuationForm
DelegateEvacuationForm
SurrogateEvacuationForm

açıkçası hangisi daha uygun bilmiyorum daha farklı seçenekler de olabilir tabi, ama "other"dan daha iyi olacaklarını düşünüyorum

2024-08-16 16:23 UTC, sanshigo345 commented
> > <img alt="Screenshot 2024-08-16 at 01 14 59" width="635" src="https://private-user-images.githubusercontent.com/38170967/358415580-37a4faed-2b20-4053-b543-cc87f1f2e4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjI3NTUsIm5iZiI6MTcyMzc2MjQ1NSwicGF0aCI6Ii8zODE3MDk2Ny8zNTg0MTU1ODAtMzdhNGZhZWQtMmIyMC00MDUzLWI1NDMtY2M4N2YxZjJlNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDIyNTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0M2U4MmRiMDczNzRkNGRiZjVhNDFjNzhmMjRiMzMwYzAzZmEzYzdlMDJjYzRiNTNmYjgxZGRhNzE5MDIyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2MGqh8FMcXXOzhDS0Le90ysFByTZ0GC78XJsEjTDLk">
> > jfyi: nerden geldiğini tam çözemedim bi süre sonra bu hata geliyor
> 
> deepl veya benzeri bir extension kullanıyor musun ?

bazı extensionlar kullanıyorum ama deepl extension ne veya benzerleri neler bilmiyorum

2024-08-16 16:23 UTC, sanshigo345 approved these changes

2024-08-16 16:30 UTC, NNakreSS commented
> > > <img alt="Screenshot 2024-08-16 at 01 14 59" width="635" src="https://private-user-images.githubusercontent.com/38170967/358415580-37a4faed-2b20-4053-b543-cc87f1f2e4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjI3NTUsIm5iZiI6MTcyMzc2MjQ1NSwicGF0aCI6Ii8zODE3MDk2Ny8zNTg0MTU1ODAtMzdhNGZhZWQtMmIyMC00MDUzLWI1NDMtY2M4N2YxZjJlNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDIyNTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0M2U4MmRiMDczNzRkNGRiZjVhNDFjNzhmMjRiMzMwYzAzZmEzYzdlMDJjYzRiNTNmYjgxZGRhNzE5MDIyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2MGqh8FMcXXOzhDS0Le90ysFByTZ0GC78XJsEjTDLk">
> > > jfyi: nerden geldiğini tam çözemedim bi süre sonra bu hata geliyor
> > 
> > deepl veya benzeri bir extension kullanıyor musun ?
> 
> bazı extensionlar kullanıyorum ama deepl extension ne veya benzerleri neler bilmiyorum

Async çalışan extensionlarin yanıt vermemesi ya da çok geç yanıt vermesinden kaynaklı bir hata. Proje bağımsız, bunu görmezden gelebiliriz.

2024-08-16 16:31 UTC, NNakreSS commented on src/components/EmergencyForm/OtherEvacuationForm.tsx
idk , aklıma isim gelmediği için gpt'ye sordum bunu önerdi , birisinde karar kıldıysan değişelim.

2024-08-16 16:37 UTC, sanshigo345 commented on src/components/EmergencyForm/OtherEvacuationForm.tsx
hala projeye süper hakim hissetmediğim için hangisi daha mantıklı bilemiyorum sen seçebilirsin, dediğim gibi herhangi biri otherdan daha iyi olur diye düşünüyorum derken seçimi sana bırakmak istemiştim. Proxy mantıklı geliyor

2024-08-17 21:24 UTC, merged

2024-08-18 05:38 UTC, agitrubard commented
@NNakreSS Pull Request başlığının açık olması konusunda @sanshigo345'ya katılıyorum. Toplu bir çözüm uygulanmışsa bile şu formda bulunan hatalar giderildi gibi bir şey yazılabilir ✅

2024-08-18 06:52 UTC, NNakreSS commented
> @NNakreSS Pull Request başlığının açık olması konusunda @sanshigo345'ya katılıyorum. Toplu bir çözüm uygulanmışsa bile şu formda bulunan hatalar giderildi gibi bir şey yazılabilir ✅

Summary varken bunun başlıkta yazmasi ne kadar mantıklı bilemedim , başlık kısa ve öz olmalı sonuçta , summary kısmının amacı bu açıklamayı sağlamak.