Environment config files added for production & development and used …
afet-yonetim-sistemi/ays-fe-landing pull request #74
Opened 2024-09-14 20:16 UTC by gafur-demirci

…for unvisible to EmergencyForm component

### Checklist

Before submitting your pull request, ensure the following:

- [ ] **Change Type:**
- [ ] Bug fix
- [x] Feature addition
- [ ] Documentation update
- [ ] Performance improvement
- [ ] Other (please specify)

- [x] **Summary:**

  - Environment config files added for production & development and used for unvisible to EmergencyForm component.

- [x] **Title and Branch Naming Conventions:**

  - The pull request title follows the
    standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
  - The branch name follows one of the conventions outlined in
    the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**

  - I have tested my changes locally on my browser, and they are working as expected.

- [x] **Code Quality:**

  - The code is formatted according to the project's coding guidelines and style.
  - The code has been reviewed to ensure its quality.
  - The code does not contain any issues flagged by ESLint.

- [x] **Documentation:**

  - Necessary documentation has been added or existing documentation has been updated.

- [x] **Reviewers and Assignees:**

  - Default reviewers have been assigned to this pull request.
  - Assignees have been added if necessary.

- [x] **Related Issue:**

  - [AYS-415](https://afetyonetimsistemi.atlassian.net/browse/AYS-415)

- [x] **Labels and Associations:**
  - No specific actions are required in the Labels and Associations section for this pull request.

2024-09-15 17:24 UTC, sanshigo345 requested changes
şu an sadece TEST ve PROD ortamı ayrımı olacağı için iki farklı .env dosyasına ihtiyaç yok. tek .env dosyası içinde yapılınabilir. 

showEmergency çok abstract bir isimlendirme olmuş o daha açıklayıcı olabilir

2024-09-16 06:13 UTC, gafur-demirci commented
showEmergencyForm ismi uygunsa bunu verebilirim, ek olarak önden hazırlanmış olması için prod env eklemiştim kalkması zorunlu ise silebilirim dosyayı, dönüşünüze göre düzenleyebilirim, teşekkürler.

2024-09-16 07:47 UTC, sanshigo345 commented
> showEmergencyForm ismi uygunsa bunu verebilirim, ek olarak önden hazırlanmış olması için prod env eklemiştim kalkması zorunlu ise silebilirim dosyayı, dönüşünüze göre düzenleyebilirim, teşekkürler.

2 dosyanın olmaması şu an için daha uygun. onun yerine .env.example dosyasına sadece ortamın test olup olmadığını belirten bir variable eklenmeli. showEmergencyForm daha uygun evet

2024-09-16 15:35 UTC, gafur-demirci commented
key değerini değiştirip env.production'ı sildim.

2024-09-16 16:41 UTC, sanshigo345 commented
> key değerini değiştirip env.production'ı sildim.

2 dosyanın da olmaması şu an için daha uygun. onun yerine .env.example dosyasına sadece ortamın test olup olmadığını belirten bir variable eklenmeli. ona göre form gösterilmemeli veya gösterilmeli

2024-09-16 18:35 UTC, gafur-demirci commented
env.example da yapılan tanımlamalar okunmuyor gibi görünüyor, onu da kaldırıp sadece env.development olması uygun mudur?

2024-09-16 18:41 UTC, sanshigo345 commented
hayır ekstra bir env dosyasına ihtiyacımız yok. example dosyası example olduğu için oradan okumaz.

.env dosyasına ve .env.example dosyasına test olduğunu belirten bi variable ekleyeceğiz. okuması gereken yer zaten .env dosyası olacak. variable ismi next conventionlarına uygun olacak ve TESTING_ENV ile bitebilir. ticketı yanlış hatırlamıyosam true ise form gözükücek.

2024-09-16 18:46 UTC, gafur-demirci commented
.env file'a key ekleyip kullandım, TESTING_ENV='test' yapmak gerekiyorsa tekrar düzenleyebilirim.

2024-09-17 06:36 UTC, sanshigo345 commented
eline sağlık, ama bi kaç eksik nokta var ben düzenleyeceğim, sonra istersen konuşabiliriz yaptığım değişiklikleri

2024-09-17 18:28 UTC, sanshigo345 approved these changes

2024-09-17 18:28 UTC, merged